import esbuild from "esbuild";

const production = process.argv[2] === "production";
const context = await esbuild.context({
  banner: {
    js: "/* This file is generated by esbuild. */",
  },
  bundle: true,
  entryPoints: ["main.ts"],
  external: ["obsidian", "electron"],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  platform: "node",
  sourcemap: production ? false : "inline",
  target: "es2020",
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}